---
- name: Install General Packages
  package:
    name: "{{ package_list }}"
    state: present
    update_cache: true
  when:
    - package_list is defined
- name: Install Ubuntu Packages
  apt:
    update_cache: true
    name: "{{ package_apt }}"
    state: present
  when:
    - ansible_os_family == "Debian"
    - package_apt is defined

- name: Install CentOS Packages
  yum:
    name: "{{ package_yum }}"
    state: present
    update_cache: true
  when:
    - ansible_os_family == "RedHat"
    - package_yum is defined
