---
- name: Install General Packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ package_list }}"
  when:
    - package_list is defined

- name: Install Ubuntu Packages
  apt:
    update_cache: true
    name: "{{ item }}"
    state: present
  loop: "{{ package_apt }}"
  when:
    - ansible_os_family == "Debian"
    - package_apt is defined

- name: Install CentOS Packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ package_yum }}"
  when:
    - ansible_os_family == "RedHat"
    - package_yum is defined
