---
- name: Install General Packages
  package:
    name:
    state: present
  with_items: package_list
  when:
    - package_list is defined

- name: Install Ubuntu Packages
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items: "{{ package_apt }}"
  when:
    - ansible_os_family == "Debian"
    - package_apt is defined

- name: Install CentOS Packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ package_yum }}"
  when:
    - ansible_os_family == "RedHat"
    - package_yum is defined
