---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    # image: centos:7
    # Initial tests with geerlingguys docker images
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    groups:
      - min
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      min:
        package_list:
          - git
          - curl
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
